///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GifModelDims {
/*
{
  "data": [
    375
  ]
} 
*/

  List<int?>? data;

  GifModelDims({
    this.data,
  });
  GifModelDims.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['data'] = arr0;
    }
    return data;
  }
}

class GifModel {
/*
{
  "url": "https://media.tenor.com/images/4e35af213c48217a1f49ecd6720c55df/tenor.gif",
  "content_description": "Hello There Happy Saturday GIF",
  "preview_url": "https://media.tenor.com/images/219d94be57d5b0c08eb96a2475f26b88/tenor.png",
  "tenor_id": "17079838",
  "dims": {
    "data": [
      375
    ]
  }
} 
*/

  String? url;
  String? contentDescription;
  String? previewUrl;
  String? tenorId;
  GifModelDims? dims;

  GifModel({
    this.url,
    this.contentDescription,
    this.previewUrl,
    this.tenorId,
    this.dims,
  });
  GifModel.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    contentDescription = json['content_description']?.toString();
    previewUrl = json['preview_url']?.toString();
    tenorId = json['tenor_id']?.toString();
    dims = (json['dims'] != null) ? GifModelDims.fromJson(json['dims']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['content_description'] = contentDescription;
    data['preview_url'] = previewUrl;
    data['tenor_id'] = tenorId;
    if (dims != null) {
      data['dims'] = dims!.toJson();
    }
    return data;
  }
}

List categories = [
  {
    "name": "embarrassed",
  },
  {
    "name": "clapping",
  },
  {
    "name": "awesome",
  },
  {
    "name": "good luck",
  },
  {
    "name": "high five",
  },
  {
    "name": "nervous",
  },
  {
    "name": "duh",
  },
  {
    "name": "aww",
  },
  {
    "name": "scared",
  },
  {
    "name": "bored",
  },
  {
    "name": "sigh",
  },
  {
    "name": "kiss",
  },
  {
    "name": "sad",
  },
  {
    "name": "good night",
  },
  {
    "name": "good morning",
  },
  {
    "name": "confused",
  },
  {
    "name": "chill out",
  },
  {
    "name": "love",
  },
  {
    "name": "happy",
  },
  {
    "name": "cry",
  },
  {
    "name": "yes",
  },
  {
    "name": "no",
  },
  {
    "name": "lol",
  },
  {
    "name": "excited",
  },
  {
    "name": "bye",
  },
  {
    "name": "sorry",
  },
  {
    "name": "congratulations",
  },
  {
    "name": "sleepy",
  },
  {
    "name": "hello",
  },
  {
    "name": "hugs",
  },
  {
    "name": "ok",
  },
  {
    "name": "please",
  },
  {
    "name": "thank you",
  },
  {
    "name": "miss you",
  },
  {
    "name": "wink",
  },
  {
    "name": "whatever",
  },
  {
    "name": "hungry",
  },
  {
    "name": "dance",
  },
  {
    "name": "annoyed",
  },
  {
    "name": "omg",
  },
  {
    "name": "crazy",
  },
  {
    "name": "shrug",
  },
  {
    "name": "smile",
  },
  {
    "name": "awkward",
  },
  {
    "name": "ew",
  },
  {
    "name": "angry",
  },
  {
    "name": "surprised",
  },
  {
    "name": "why",
  },
  {
    "name": "thumbs up",
  },
  {
    "name": "wow",
  },
  {
    "name": "ouch",
  },
  {
    "name": "oops",
  },
  {
    "name": "youre welcome",
  },
  {
    "name": "lazy",
  },
  {
    "name": "stressed",
  }
];
