name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  csv: ^5.0.1
  dart_frog: ^0.3.0
  dio: ^5.1.1
  hive: ^2.2.3
  supabase: ^1.6.3
  schedurio_utils:
    path: ../packages/schedurio_utils

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
