create table "public"."info" (
    "id" bigint generated by default as identity not null,
    "twitter" jsonb,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX info_pkey ON public.info USING btree (id);

alter table "public"."info" add constraint "info_pkey" PRIMARY KEY using index "info_pkey";


