create table "public"."drafts" (
    "id" bigint generated by default as identity not null,
    "tweets" jsonb,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX drafts_pkey ON public.drafts USING btree (id);

alter table "public"."drafts" add constraint "drafts_pkey" PRIMARY KEY using index "drafts_pkey";


