create table "public"."queue" (
    "id" bigint generated by default as identity not null,
    "cron_text" text,
    "status" character varying,
    "created_at" timestamp with time zone default now(),
    "scheduled_at" text,
    "updated_at" timestamp with time zone default now(),
    "tweets" jsonb,
    "cron_media" text,
    "media_ids" jsonb,
    "twitter_id" bigint
);


CREATE UNIQUE INDEX queue_pkey ON public.queue USING btree (id);

alter table "public"."queue" add constraint "queue_pkey" PRIMARY KEY using index "queue_pkey";


